### ISSUE TITLE
This line seems useless

### ISSUE THREAD

**Issue by jip** [jsoftware/math_misc#3]
https://github.com/jsoftware/math_misc/blob/94d01b343b0a42bb9ccabb648e886cdb18b0bda5/jacobi.ijs#L53

since (1) name `countW` isn't defined, (2) `count` noun isn't read anywhere else.

**Comment by rdm** [comment]
Yes... that W looks like a typo that wasn't caught because it didn't break anything.

And, I agree: count itself looks like a leftover adhoc debugging mechanism -- so probably all lines referencing count can be removed.

**Comment by jip** [comment]
I might prepare PR if addon holders have no objections.

**Comment by rdm** [comment]
I'd say go for it.

This isn't a high activity repository, and it's not like there's anything to lose here.
